---
name: Test

on:
    pull_request:
    push:
        branches: [main]

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: [8.1]
        name: html2jsonld php ${{ matrix.php-versions }} unit tests
        steps:
            - name: Set up php${{ matrix.php-versions }}
              uses: shivammathur/setup-php@master
              with:
                  php-version: ${{ matrix.php-versions }}
            - name: Checkout HTML2JSONLD-PHP
              uses: actions/checkout@v3
            - name: Install dependencies
              run: composer install
            - name: Run tests
              run: vendor/bin/phpunit tests/unit
